login_man/login_man/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from man_log import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('man_log.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^message/', include('message_man.urls')),
    url(r'^content/', views.content,name='index'),
    url(r'^$', views.index),

] + static(settings.STATIC_URL,document_root=settings.STATIC_URL)

login_man/man_log/urls.py
from django.conf.urls import url
from . import views

app_name = 'man_log'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    # url(r'^login/', views.login_man),
    # url(r'^logout', views.logout),
    # url(r'^login', views.index),
]

login_man/message_man/urls.py
from django.conf.urls import url
from . import views

app_name = 'message_man'
urlpatterns = [
	url(r'^add/', views.message_ajax),
	url(r'^weidu/', views.message_num),
]

login_man/man_log/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)

    class Meta(AbstractUser.Meta):
        pass

login_man/message_man/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
from man_log import models as mmode


# 信息发送时间 信息标题 信息内容  信息发送人  信息接收人  信息状态
class message_man(models.Model):
	time = models.DateTimeField('datatime', default=timezone.now)
	message_title = models.CharField(max_length=40)
	message_txt = models.TextField(max_length=40)
	message_sendname = models.CharField(max_length=150)
	message_recivename = models.CharField(max_length=150)
	message_status = models.IntegerField( default=1)

login_man/man_log/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

login_man/man_log/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.http import HttpResponse, HttpResponseRedirect
from man_log.models import User
import json
from django.contrib.auth.decorators import login_required


def register(request):
	redirect_to = request.POST.get('next', request.GET.get('next', ''))
	# 只有当请求为 POST 时，才表示用户提交了注册信息
	if request.method == 'POST':
		# request.POST 是一个类字典数据结构，记录了用户提交的注册信息
		# 这里提交的就是用户名（username）、密码（password）、邮箱（email）
		# 用这些数据实例化一个用户注册表单
		form = RegisterForm(request.POST)

		# 验证数据的合法性
		if form.is_valid():
			# 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
			form.save()
			if redirect_to:
				return redirect(redirect_to)
			else:
				return HttpResponseRedirect('/content/')
			# 注册成功，跳转内容管理页面
			return HttpResponseRedirect('/content/')
	else:
		# 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
		form = RegisterForm()

	# 渲染模板
	# 如果用户正在访问注册页面，则渲染的是一个空的注册表单
	# 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
	return render(
		request,
		'man_log/register.html',
		context={
			'form': form,
			'next': redirect_to})

@login_required
def logout(request):
	return render(request, 'man_log/logout.html')


def login(request):
	return render(request, 'registration/login.html')

def index(request):
	return render(request,'index.html')


@login_required
def content(request):
	usersnames = User.objects.all()
	mannames = {'username': []}
	for x in usersnames:

		mannames['username'].append(x.username)
	return render(request, 'content.html', {'mannames': json.dumps(mannames)})

login_man/message_man/views.py
from django.shortcuts import render, HttpResponse
from .models import message_man
import json, time
from django.contrib.auth.decorators import login_required


# Create your views here.

#  接收网页a、b、receivename3个参数
@login_required
def message_ajax(request):
    a = request.POST.get('a', 1)
    b = request.POST.get('b', 1)
    receivename = request.POST.get('receivename', 1)
    if a is not None and b is not None and receivename is not None:
        m = message_man.objects.create(
            message_title=a,
            message_txt=b,
            message_recivename=receivename,
            message_sendname=str(
                request.user),
            message_status=2)
        m.save()
        return HttpResponse(
            json.dumps({"name": "success", "year": time.ctime()}),
            content_type="application/json"
        )




# 根据提交的当前用户  提取未读邮件 并将内容传递给前台
@login_required
def message_num(request):
    weidu_messages = message_man.objects.filter(
        message_recivename=str(request.user), message_status=2
    )
    msg_title = []
    msg_content = []
    msg_sendname = []
    msg_time = []
    for x in weidu_messages:
        msg_title.append(x.message_title)
        msg_content.append(x.message_txt)
        msg_sendname.append(x.message_sendname)
        msg_time.append(str(x.time))
    return render(request, 'registration/message.html', {'msg_title':msg_title,'msg_content':msg_content,'msg_sendname':msg_sendname,'msg_time':msg_time})

login_man/templates/content.html
{% extends 'registration/base.html' %}
{% block title %}
    <title>首页</title>
<link rel="stylesheet" href="https://cdn.staticfile.org/mobi.css/2.0.0-beta.1/mobi.min.css">

{% endblock %}
{% block content %}
    <div>
        <h1 class="logo"><a href="#">用户内容管理系统</a></h1>
        {% if user.is_authenticated %}
            {% csrf_token %}
            <p>你已登录，欢迎你：<a href="/admin/" id="usernames">{{ user.username }}</a></p>
            <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a></button>
            <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
            </button>
            <button class="btn btn-default" id="m"><a>发送站内信</a></button>
            <button class="btn btn-default" id="message"><a id="message——nums" href="/message/weidu/" methods="GET">信箱</a></button>
            <div id="p" hidden="hidden">
                <label>站内信息发送人选择</label>
                <select name="" id="name_list">
                </select>
                <form action="/add/" method="POST">
                    {% csrf_token %}
                    <input rows="3" cols="50" id="b">
                    <textarea rows="3" cols="80" id="a"></textarea>
                    <p>发送成功: <span id='result'></span></p>
                    <p>js: <span id='jstest'></span></p>
                    <button class="btn btn-default" type="button" id='sum' value="">提交</button>
                </form>
            </div>
            <script>
                var name_list = JSON.parse('{{ mannames|safe }}');
                var arr = name_list.username
                $.each(arr, function () {
                    var usernames=$('#usernames').val()
                    console.log(this);
                    if (this==usernames)
                    {
                        return true
                        }
                    else{
                        $("#name_list").append("<option value='"+this+"'>" + this + "</option>");
                    }
                    }
                );
                $(document).ready(function () {

                    $("#m").click(function () {
                        $("#p").show();
                    });
                    $("#sum").click(function () {
                        var a = $('#a').val();
                        var b = $('#b').val();
                        var receivename=$('#name_list').val()
                        $.ajax({
                            method: "POST",
                            url: '/message/add/',
                            data: {'a': a, 'b': b,'receivename':receivename, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                            datatype: "json",
                            success: function (msg) {
                                console.log(msg)
                                $("#result").html(msg.name);
                                $("#jstest").html(msg.year);
                            }
                        })
                    });
                });
            </script>
        {% else %}
            <p>你还没有登录，请
                <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                或者
                <button class="btn btn-default"><a href="{% url 'man_log:register' %}">注册</a></button>
            </p>
        {% endif %}
    </div>
{% endblock %}

login_man/templates/index.html
{% extends 'registration/base.html' %}
{% block title %}
    <title>首页</title>
{% endblock %}
{% block content %}
    {% load static %}
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Brand</a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="dropdown">
							 <a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">最新信息<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									 <a href="#">产品信息</a>
								</li>
								<li>
									 <a href="#">公司信息</a>
								</li>
								<li>
									 <a href="#">业内信息</a>
								</li>
							</ul>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control"  placeholder="请输入需要查找的内容">
						</div> <button type="submit" class="btn btn-default">Submit</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							 <a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">请登录或者注册<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									 <a href="{% url 'login' %}?next={{ request.path }}">登录</a>
								</li>
								<li>
									 <a href="{% url 'man_log:register' %}">注册</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>

			</nav>
			<div class="jumbotron">
				<h1>
					Hello, world!
				</h1>
				<p>
					hello world two!
				</p>
				<p>
					 <a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row clearfix">
		<div class="col-md-4 column">
			<h2>
				最新信息
			</h2>
			<table class="table table-striped">
                <tbody>
                    <tr>
                        <td>Tanmay</td>
                        <td>Bangalore</td>
                        <td>560001</td>
                        <td>2017.8.27</td>
                    </tr>
                <tr>
                     <td>Sachin</td>
                     <td>Mumbai</td>
                     <td>400003</td>
                    <td>2017.8.27</td>
                </tr>
                <tr>
                    <td>Uma</td>
                    <td>Pune</td>
                    <td>411027</td>
                    <td>2017.8.27</td>
                </tr>
                </tbody>
            </table>
			<p>
				 <a class="btn" href="#">查看更多»</a>
			</p>
		</div>
		<div class="col-md-4 column " style="height: 250px">
			<h2>
				Heading
			</h2>
			<img src="{% static "/jpg/products.jpg" %} " alt="Cinque Terre" width="304px" height="200px">
			<p>
				 <a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4 column">
			<h2>
				Heading
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				 <a class="btn" href="#">View details »</a>
			</p>
		</div>
	</div>
</div>
{% endblock %}

login_man/templates/man_log/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html><!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>

</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
          <h1>你已经成功退出</h1>
            <a href="../index.html">首页</a>
        </div>
    </div>
</div>
</body>
</html>

login_man/templates/man_log/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>注册</h3>
                <form class="form" action="{% url 'man_log:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap tex  t-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>